# render.yaml
# -------------
# Defines one database + one web service on the Free plan.
# We’ll pass ADMIN_* via envVars and let your app create the Admin if it’s missing.

databases:
  - name: database
    plan: free
    postgresMajorVersion: 16

services:
  - type: web
    name: evershop-app
    runtime: node         # “env: node” is deprecated; use runtime
    plan: free
    branch: master
    healthCheckPath: /
    buildCommand: >
      npm install &&
      npm run compile -w @evershop/postgres-query-builder &&
      npm run compile &&
      npm run build
    startCommand: npm run start
    envVars:
      # Database connection
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_USER
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: database
          property: database

      # Admin‑seeding credentials
      - key: ADMIN_NAME
        value: "Admin"
      - key: ADMIN_EMAIL
        value: "khoualdiyassin26@gmail.com"
      - key: ADMIN_PASSWORD
        value: "admin123"
