databases:
  - name: database
    plan: free
    postgresMajorVersion: 16

services:
  - type: web
    name: evershop-app
    runtime: node     # use `runtime` instead of the deprecated `env`
    plan: free
    branch: master
    healthCheckPath: /
    buildCommand: >
      npm install &&
      npm run compile -w @evershop/postgres-query-builder &&
      npm run compile &&
      npm run build
    preDeployCommand: >            # ← runs after build, before start
      npm run user:create \
        -w @evershop/evershop \
        --name 'Admin' \
        --email 'khoualdiyassin26@gmail.com' \
        --password 'admin123'
    startCommand: npm run start
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_USER
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: database
          property: database
