databases:
  - name: database
    plan: free
    postgresMajorVersion: 16

services:
  # The Evershop web service
  - type: web
    name: evershop-app
    env: node
    plan: free
    branch: main # or your default branch
    healthCheckPath: / 
    buildCommand: "npm install && npm run compile && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_USER
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: database
          property: database
      # Admin credentials as requested
      - key: ADMIN_EMAIL
        value: khoualdiyassin26@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
