# render.yaml
# -------------
# Defines one database + one web service on the Free plan.
# We’ll pass ADMIN_* via envVars and let your app create the Admin if it’s missing.

databases:
  - name: database
    plan: free
    postgresMajorVersion: 16

services:
  - type: web
    name: evershop-app
    runtime: node         # “env: node” is deprecated; use runtime
    plan: free
    branch: master
    healthCheckPath: /
    buildCommand: >
      npm install &&
      npm run compile -w @evershop/postgres-query-builder &&
      npm run compile &&
      npm run setup &&
      npm run build
    startCommand: npm run start
    envVars:
      # Database connection
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_USER
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: database
          property: database

      # This key is used by Render to automatically set the environment variable for the web service.
      # For a new service, you should also set this to a unique value in the Render dashboard.
      - key: PORT
        value: 3000

      # Set the Node.js environment to production
      - key: NODE_ENV
        value: production

      # Admin-seeding credentials (ADMIN_FULLNAME, ADMIN_EMAIL, ADMIN_PASSWORD)
      # have been removed from this file.
      # IMPORTANT: You MUST set them as secret environment variables in the Render.com dashboard for your service.
