services:
  # A PostgreSQL database
  - type: postgres
    name: database
    plan: starter
    postgresMajorVersion: 16

  # The Evershop web service
  - type: web
    name: evershop-app
    env: node
    plan: starter
    branch: main # or your default branch
    healthCheckPath: / 
    buildCommand: "npm install && npm run compile && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: DB_HOST
        fromService:
          type: postgres
          name: database
          property: host
      - key: DB_PORT
        fromService:
          type: postgres
          name: database
          property: port
      - key: DB_USER
        fromService:
          type: postgres
          name: database
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: database
          property: password
      - key: DB_NAME
        fromService:
          type: postgres
          name: database
          property: database
      # Admin credentials as requested
      - key: ADMIN_EMAIL
        value: khoualdiyassin26@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
