databases:
  - name: database
    plan: free
    postgresMajorVersion: 16

services:
  # The Evershop web service
  - type: web
    name: evershop-app
    env: node
    plan: free
    branch: master
    healthCheckPath: / 
    buildCommand: "npm install && npm run compile -w @evershop/postgres-query-builder && npm run compile && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_USER
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: database
          property: database

  # Job to create the admin user. This runs once after the first successful deploy.
  - type: job
    name: setup-admin
    plan: free
    startCommand: "npm run user:create -w @evershop/evershop -- --name 'Admin' --email 'khoualdiyassin26@gmail.com' --password 'admin123'"
